baseurl = "https://.github.io"
DefaultContentLanguage = "en"
title = "ACFR Planning and Control Reading Group"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
 homeTitle = "ACFR Planning and Control Reading Group" # Set a different text for the header on the home page
  # subtitle = "Weekly Discussions on Plann"
  mainSections = ["post","posts"]
  logo = "img/pacrg-logo.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = false
  socialShare = false
  delayDisqus = false
  showRelatedPosts = false
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

# [[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
[[Params.bigimg]]
 src = "img/tara_traj_opt.png"
 desc = "Tara's Centroidal Motion and Footstep Planning"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Michael Somerfield"
  website = "juraph.com"
  email = "msom0518@sydney.edu.au"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Previous Talks"
    url = "previous-talks/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Join"
    url = "page/subscribe/"
    weight = 3
